# managed-crates.toml
#
# Tracks crates that RS-CA currently manages or has decided to manage.
#
# FORMAT
# [crates]
# <crate-name> = "<stage>"
# <crate-name> = { stage = "<stage>", new_name = "<fork-name-if-renamed>" }
#
# STAGES
# - "contact"  : Trying to contact the original author/owner to arrange transfer.
# - "hardfork" : A hard fork has been created under RS-CA.
# - "transfer" : Ownership/maintenance has been transferred to RS-CA.
#
# Notes:
# - Use the simple string form when you only need the stage.
# - Use the object form if the fork must live under a different name (new_name).
# - More stages may be added over time.

[crates]
serde_yaml = "contact"
paste = "contact"

# Example using the object form (fork renamed):
# old_unmaintained = { stage = "hardfork", new_name = "old-unmaintained-rs" }

# Example already transferred:
# regex = "transfer"
